project:
  type: website

website:
  title: "stats140xp_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - Work Experiences.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

